#include <stdio.h>
#include <string.h>
#include "game.h"
#include "print_grid.h"
#include "sleep_ms.h"

// We have to cover three different cases: a cell can either have
// three neighbors (a), five neighbors (b), or eight neigbors (c), depending on the
// position wrt. (with respect to) the boundaries
//
// cosidered cell = x, neighbors = 1, . = some more lines and columns
//
// (a) x 1 0 . 0 < line with index y = 0
//     1 1 0 . 0
//     . . . . .
//     0 0 0 . 0 < line with index y = GRID_Y -1
//     ^       ^ col with index x = GRID_X - 1
//     |
//     col with index x = 0
//
// (b) 1 1 0 . 0 < line with index y = 0
//     x 1 0 . 0
//     1 1 0 . 0
//     . . . . .
//     0 0 0 . 0 < line with index y = GRID_Y -1
//     ^       ^ col with index x = GRID_X - 1
//     |
//     col with index x = 0
//
// (c) 1 1 1 . 0 < line with index y = 0
//     1 x 1 . 0
//     1 1 1 . 0 
//     . . . . .
//     0 0 0 . 0 < line with index y = GRID_Y -1
//     ^       ^ col with index x = GRID_X - 1
//     |
//     col with index x = 0
//
// SOLUTION STRATEGY:
// FIRST ADD UP ADJACENT CELLS, INCREMENT non (number of neighbors) IF THEY ARE LIVING
//
// ANOTHER SOLUTION WOULD BE TO USE CYCLIC BOUNDARIES i.e. if you leave
// the arry on top, you enter on the bottom (resp. leave left, you enter on the right like Bernd
// das Brot). In this case, any cell has always 8 neighbors that have to be checked...
// Behavior could be switched by a macro variable
// CYCLIC_BC = 1
//
// up to you... this text was generated by human intelligence only... peace out...
// /

// int number_of_neighbors(int y, int x, grid[GRID_Y][GRID_X]){
// int non = 0; // number of neighbors
//
// if ((x>0) && (x<GRID_X) && (y>0) && (y<GRID_Y)){  // CASE (c)
// for (int y_ = y-1; y_ <= y+1; y_++){
// for (int x_ = x-1; (x_ <= x+1) && !((x==x_)&&(y_==y_)); x_++){
// if (grid[y_][x_] == '1'){
// non++;
//
// .....
// Diese Lösung war zu kompliziert, die Einzelfälle können einfach innerhalb der Schleife
// abgefangen werden, mache nur "continue" wenn ein Index 0 unterschreitet bzw. GRID_X,Y-1 überschreitet.
// .....
// return (non); // like a frenchman denying...
// }

static int number_of_neighbors(int y, int x, char grid[GRID_Y][GRID_X]) // static: nur innerhalb dieser Datei verfügbar
									// ansonsten müsste man die Fct. in game.h deklarieren..
{
	int non = 0;

	for (int y_ = y - 1; y_ <= y + 1; y_++) {
		for (int x_ = x - 1; x_ <= x + 1; x_++) {

			// own cell
			if (y_ == y && x_ == x)
				continue;

			// outside grid
			if (y_ < 0 || y_ >= GRID_Y ||
					x_ < 0 || x_ >= GRID_X)
				continue;

			if (grid[y_][x_] == 1)
				non++;
		}
	}

	return non; // like a frenchman denying...
}



void game(char grid[][GRID_X])
{
	printf("game started...\n");
	int generation = 0;
	while (1) {
		printf("Generation: %d\n",generation);
		print_grid(grid);
		sleep_ms(1000);
		char ingrid[GRID_Y][GRID_X]={0}; // iteration grid :)
		for (int j = 0; j < GRID_Y; j++){ // little reminder: j++ and ++j are equivalent in this case if there is 
						  // no return value... but what happens if there IS?!?
			for (int i = 0; i < GRID_X; i++){
				int non = number_of_neighbors(j,i,grid);
				char setval = 0; // char ist ein ganzzahliger Datentyp
				if (RULESET[non]=='0'){
					// do not do anything
				}
				else if(RULESET[non]=='C'){
					setval = grid[j][i];
				}
				else if(RULESET[non]=='1'){
					setval = 1;
				}
				ingrid[j][i] = setval; // Wenn wir grid bzw. ingrid als char-Array definieren, sollten wir setval oben nicht als int definieren!
						       // Sonst gibt's ein Warning wegen impliziter Konvertierung...

			}
		}
		memcpy(grid, ingrid, sizeof ingrid);
		generation ++;
	}
}
